### ISSUE TITLE
Not a complete drop-in replacement for Email::Address

### ISSUE THREAD

**Issue by dlucredativ** [pali/Email-Address-XS#4]
Hi,

I stumbled upon a difference between `Email::Address` and `Email::Address::XS` during the migration of some code that lead to more adaptations than a simple `s/Email::Address/Email::Address::XS/g`.

```
root@8803cfd92bb9:~# perl -MEmail::Address -MData::Dumper -E 'print Dumper [Email::Address->parse("foo")]'
$VAR1 = [];
root@8803cfd92bb9:~# perl -MEmail::Address::XS -MData::Dumper -E 'print Dumper [Email::Address::XS->parse("foo")]'
$VAR1 = [
          bless( {
                   'host' => undef,
                   'original' => 'foo',
                   'comment' => undef,
                   'invalid' => 1,
                   'user' => undef,
                   'phrase' => 'foo'
                 }, 'Email::Address::XS' )
        ];
```

**Comment by pali** [comment]
Those blessed parts are private internal members of Email::Address::XS object. I hope that you are not going to read or touch private parts of Email::Address::XS object. This is something which must never been used as internal parts are not part of public API and are subject of change in any time. Public API is described in documentation: https://metacpan.org/pod/Email::Address::XS

If you provide garbage (more precisely invalid RFC email address) on input, then output Email::Address::XS object would be marked as invalid. For detection if parsed string was valid, there is `is_valid` method, see: https://metacpan.org/pod/Email::Address::XS#is_valid

Moreover Email::Address has lot of bugs in it parser, so yes, it returns different (and wrong) output as Email::Address::XS which aims to be valid. So in this case it is not compatible, as Email::Address::XS would return correct output as opposite of incorrect one returned by Email::Address. And handling of invalid input drops into this category too -- simple ignorance without ability to distinguish between correct and incorrect one is a bug too. Email::Address::XS is there for parsing headers from emails -- which are by its definition untrusted input and such thing needs to be handled very carefully, by both caller and callee.

Therefore I would close this issue as Email::Address::XS is not going to re-implement (useless and wrong) Email::Address parser. If you have other questions about usage or need to port code, feel free to ask.

**Comment by dlucredativ** [comment]
Thanks for your answer,

I am aware of the `is_valid` method and I have used it to fix the automated tests in my migrated code.
Also, I did not intend to persuade you to re-implement Email::Address behaviour by opening this issue, but I think that a more precise description of the modules compatibility would be useful, If you could provide such.

As we have seen, for the general case one cannot substitute `Email::Address->parse(...)` by `Email::Address::XS->parse(...)`, but maybe one can substitute by `grep {$_->is_valid} Email::Address::XS->parse(...)` instead? Or could there be corner cases so that even the latter substitution is not generally correct? I may also be true, that the two implementations are too complex to know if there are such corner cases.

So, If you know a more precise description of differences in behaviour, it would be nice if it were documented.

**Comment by pali** [comment]
It is quite difficult to describe what would change in migration steps when you are trying to parse invalid email addresses, or input which contains mix of valid and invalid...

Also it depends on more factors. E.g.: Are you interested in invalid parts of input? Because then you really want to replace `Email::Address->parse(...)` by `Email::Address::XS->parse(...)`. If not then you need to do some filtering. Email viewer programs are probably interested -- they should show to user what is really in From/To/Cc headers. Interactive email reply tool is partially interested -- it should show error message to user "sorry, I'm unable to send message to this broken address". And automated/batched/scripted email reply tools in some cases are not interested in invalid email addresses -- as they cannot send to them anything.

If you have any idea how to improvement documentation, then feel free to prepare some changes. Looks like that all these problems are only about processing of (partially) invalid/incorrect input. So maybe some separate section for it?

**Comment by dlucredativ** [comment]
I am potentially interested in invalid parts of the input, if those parts look like an email address. For example, both the native and XS libraries parse `"spoofed@domain.tld" <some@mail.com>` with the phrase set to `spoofed@domain.tld` which I can feed again to the parser and obtain a second address.
With the XS parser I have now to take care of phrases that won't get reduced to smaller parts from some point onwards.

A separate section for some exemplary corner cases sounds reasonable. I can submit a merge request when I have some time.
